package com.rainalarm.app.domain

/** One polygon in the versioned, offline-generated nominal radar coverage. */
data class MeteoNominalCoveragePolygon(
    val exterior: List<GeoPoint>,
    val holes: List<List<GeoPoint>> = emptyList(),
)

/**
 * Versioned nominal structural reach for supported MeteoGroup regional products.
 *
 * Generated by tools/generate_meteo_uk_nominal_coverage.py from the 16 Met Office/Jersey
 * sites in Factsheet 15 (255 km), Dublin (250 km) and Shannon (248.5 km). The geodesic
 * union is clipped to the exact native UK source-raster footprint, then topology-preserving
 * simplified with 729.6 m measured Hausdorff error. This is not live availability
 * and deliberately says nothing about terrain, beam blockage, outages, or current echoes.
 *
 * Contains public sector information licensed under the Open Government Licence v3.0.
 * Met Eireann radar open data is licensed under CC BY 4.0.
 */
object MeteoNominalCoverage {
    const val GEOMETRY_VERSION = "2026-09-25"
    const val MAX_SIMPLIFICATION_ERROR_METRES = 729.577

    private val uk: List<MeteoNominalCoveragePolygon> = listOf(
            MeteoNominalCoveragePolygon(
                exterior = listOf(
                    GeoPoint(47.7116455, -5.3410632),
                    GeoPoint(47.7252141, -4.8278392),
                    GeoPoint(47.5624376, -4.5949926),
                    GeoPoint(47.4317500, -4.3715298),
                    GeoPoint(47.2924232, -4.0838957),
                    GeoPoint(47.1918314, -3.8299894),
                    GeoPoint(47.1060778, -3.5650652),
                    GeoPoint(47.0357429, -3.2909555),
                    GeoPoint(46.9813007, -3.0095313),
                    GeoPoint(46.9431170, -2.7226933),
                    GeoPoint(46.9191105, -2.3740499),
                    GeoPoint(46.9174405, -2.0820890),
                    GeoPoint(46.9324570, -1.7909054),
                    GeoPoint(46.9640594, -1.5024393),
                    GeoPoint(47.0120360, -1.2186201),
                    GeoPoint(47.0760647, -0.9413582),
                    GeoPoint(47.1557145, -0.6725376),
                    GeoPoint(47.2504474, -0.4140071),
                    GeoPoint(47.4071695, -0.0727790),
                    GeoPoint(47.5900818, 0.2399766),
                    GeoPoint(47.7967159, 0.5197399),
                    GeoPoint(48.0242550, 0.7622997),
                    GeoPoint(48.2695614, 0.9638134),
                    GeoPoint(48.5292093, 1.1208694),
                    GeoPoint(48.7995215, 1.2305542),
                    GeoPoint(49.0444985, 1.2861280),
                    GeoPoint(49.0977929, 1.6248499),
                    GeoPoint(49.1615929, 1.9136596),
                    GeoPoint(49.2409658, 2.1937653),
                    GeoPoint(49.3353806, 2.4632559),
                    GeoPoint(49.4676325, 2.7700052),
                    GeoPoint(49.5927627, 3.0096379),
                    GeoPoint(49.7305525, 3.2328697),
                    GeoPoint(49.8800564, 3.4380300),
                    GeoPoint(50.0074012, 3.5880774),
                    GeoPoint(50.1753270, 3.7567738),
                    GeoPoint(50.3159262, 3.8757624),
                    GeoPoint(50.4984509, 4.0034439),
                    GeoPoint(50.6490748, 4.0880053),
                    GeoPoint(50.8419653, 4.1708373),
                    GeoPoint(50.9990857, 4.2182323),
                    GeoPoint(51.1977764, 4.2532399),
                    GeoPoint(51.4375991, 4.2589225),
                    GeoPoint(51.6764679, 4.2243464),
                    GeoPoint(51.9117348, 4.1492615),
                    GeoPoint(52.1407500, 4.0338827),
                    GeoPoint(52.3608937, 3.8789166),
                    GeoPoint(52.5696083, 3.6855824),
                    GeoPoint(52.7644323, 3.4556244),
                    GeoPoint(52.9409254, 3.1947412),
                    GeoPoint(53.1541098, 3.2491807),
                    GeoPoint(53.3935366, 3.2705511),
                    GeoPoint(53.5931850, 3.2563426),
                    GeoPoint(53.8306301, 3.2004186),
                    GeoPoint(54.0632392, 3.1020205),
                    GeoPoint(54.3249760, 2.9341211),
                    GeoPoint(54.5380867, 2.7458254),
                    GeoPoint(54.7617039, 2.4875362),
                    GeoPoint(54.9805376, 2.4875481),
                    GeoPoint(55.1794689, 2.4555727),
                    GeoPoint(55.3760163, 2.3929798),
                    GeoPoint(55.5686401, 2.2998063),
                    GeoPoint(55.7558086, 2.1763469),
                    GeoPoint(55.9360112, 2.0231669),
                    GeoPoint(56.1077725, 1.8411115),
                    GeoPoint(56.2948857, 1.5946599),
                    GeoPoint(56.4061146, 1.7090028),
                    GeoPoint(56.5495067, 1.8364641),
                    GeoPoint(56.6973584, 1.9464384),
                    GeoPoint(56.8489984, 2.0382195),
                    GeoPoint(57.0037304, 2.1111641),
                    GeoPoint(57.1608354, 2.1646972),
                    GeoPoint(57.3195744, 2.1983192),
                    GeoPoint(57.4791914, 2.2116113),
                    GeoPoint(57.6389165, 2.2042428),
                    GeoPoint(57.7979690, 2.1759772),
                    GeoPoint(57.9555615, 2.1266786),
                    GeoPoint(58.1109033, 2.0563181),
                    GeoPoint(58.2632046, 1.9649792),
                    GeoPoint(58.4116807, 1.8528639),
                    GeoPoint(58.6599870, 1.6077162),
                    GeoPoint(58.7939941, 1.4405216),
                    GeoPoint(58.9213583, 1.2544288),
                    GeoPoint(59.0413834, 1.0502487),
                    GeoPoint(59.1534056, 0.8289232),
                    GeoPoint(59.2567990, 0.5915229),
                    GeoPoint(59.3509797, 0.3392434),
                    GeoPoint(59.4354113, 0.0733994),
                    GeoPoint(59.5096085, -0.2045830),
                    GeoPoint(59.5731418, -0.4931749),
                    GeoPoint(59.6256408, -0.7907562),
                    GeoPoint(59.6667980, -1.0956278),
                    GeoPoint(59.7019323, -1.4842770),
                    GeoPoint(59.7167876, -1.7990277),
                    GeoPoint(59.7197630, -2.1151778),
                    GeoPoint(59.7108411, -2.4308611),
                    GeoPoint(59.6856319, -2.7934194),
                    GeoPoint(59.8774309, -3.1358351),
                    GeoPoint(60.0604811, -3.5568558),
                    GeoPoint(60.2149038, -4.0236623),
                    GeoPoint(60.3224069, -4.4544920),
                    GeoPoint(60.4168474, -4.9854098),
                    GeoPoint(60.4763256, -5.5379084),
                    GeoPoint(60.4997623, -6.1020969),
                    GeoPoint(60.4908232, -6.5872476),
                    GeoPoint(60.4700171, -6.9080824),
                    GeoPoint(60.4374679, -7.2246232),
                    GeoPoint(60.3528695, -7.7626860),
                    GeoPoint(60.2344625, -8.2724544),
                    GeoPoint(60.1524136, -8.5476525),
                    GeoPoint(60.0604811, -8.8092553),
                    GeoPoint(59.8774309, -9.2302760),
                    GeoPoint(59.7611809, -9.4477668),
                    GeoPoint(59.6372601, -9.6471493),
                    GeoPoint(59.4040145, -9.9498911),
                    GeoPoint(59.2626119, -10.0952892),
                    GeoPoint(59.1162421, -10.2199372),
                    GeoPoint(58.9656756, -10.3234491),
                    GeoPoint(58.7727578, -10.4227358),
                    GeoPoint(58.5760465, -10.4883711),
                    GeoPoint(58.3770870, -10.5204076),
                    GeoPoint(58.1774159, -10.5191638),
                    GeoPoint(57.9785495, -10.4852050),
                    GeoPoint(57.7819732, -10.4193217),
                    GeoPoint(57.5891317, -10.3225095),
                    GeoPoint(57.4384872, -10.2235783),
                    GeoPoint(57.2558464, -10.0741795),
                    GeoPoint(57.0806979, -9.8975592),
                    GeoPoint(56.9142592, -9.6953135),
                    GeoPoint(56.7576721, -9.4691542),
                    GeoPoint(56.6119982, -9.2208940),
                    GeoPoint(56.4782143, -8.9524329),
                    GeoPoint(56.3637025, -8.6822049),
                    GeoPoint(56.2267660, -8.9828102),
                    GeoPoint(56.0564252, -9.2847562),
                    GeoPoint(55.8687889, -9.5505712),
                    GeoPoint(55.6661428, -9.7775681),
                    GeoPoint(55.4509170, -9.9636500),
                    GeoPoint(55.2256499, -10.1073087),
                    GeoPoint(54.9929531, -10.2076105),
                    GeoPoint(54.7793091, -10.2603476),
                    GeoPoint(54.7055509, -10.5489913),
                    GeoPoint(54.6113636, -10.8429115),
                    GeoPoint(54.5020365, -11.1201100),
                    GeoPoint(54.3785179, -11.3783321),
                    GeoPoint(54.2418693, -11.6155442),
                    GeoPoint(54.0932534, -11.8299502),
                    GeoPoint(53.9339209, -12.0200030),
                    GeoPoint(53.7996275, -12.1536346),
                    GeoPoint(53.6243868, -12.2967713),
                    GeoPoint(53.4422854, -12.4125897),
                    GeoPoint(53.2547855, -12.5005167),
                    GeoPoint(53.1018965, -12.5505488),
                    GeoPoint(52.9084306, -12.5876079),
                    GeoPoint(52.7137447, -12.5964513),
                    GeoPoint(52.5193247, -12.5773869),
                    GeoPoint(52.3649650, -12.5423779),
                    GeoPoint(52.1371073, -12.4577610),
                    GeoPoint(51.9521339, -12.3587668),
                    GeoPoint(51.7730563, -12.2349701),
                    GeoPoint(51.6011584, -12.0875429),
                    GeoPoint(51.4376594, -11.9177871),
                    GeoPoint(51.2541573, -11.6866107),
                    GeoPoint(51.1130656, -11.4728689),
                    GeoPoint(50.9593992, -11.1935035),
                    GeoPoint(50.8454046, -10.9436486),
                    GeoPoint(50.7266377, -10.6260367),
                    GeoPoint(50.6434678, -10.3487071),
                    GeoPoint(50.5634580, -10.0035679),
                    GeoPoint(50.5137987, -9.7079392),
                    GeoPoint(50.4751183, -9.3465127),
                    GeoPoint(50.4605603, -9.0420968),
                    GeoPoint(50.4626478, -8.7243493),
                    GeoPoint(50.3083240, -8.7593776),
                    GeoPoint(50.1487998, -8.7779819),
                    GeoPoint(49.8690223, -8.7687311),
                    GeoPoint(49.5920207, -8.7072411),
                    GeoPoint(49.3218369, -8.5952788),
                    GeoPoint(49.0623503, -8.4352546),
                    GeoPoint(48.8172297, -8.2301499),
                    GeoPoint(48.5898916, -7.9834457),
                    GeoPoint(48.3834636, -7.6990547),
                    GeoPoint(48.2007522, -7.3812570),
                    GeoPoint(48.0648925, -7.0857402),
                    GeoPoint(47.9324681, -6.7182652),
                    GeoPoint(47.8425786, -6.3874365),
                    GeoPoint(47.7754176, -6.0454071),
                    GeoPoint(47.7316329, -5.6954951),
                    GeoPoint(47.7116455, -5.3410632),
                ),
                holes = listOf(),
            )
    )

    /** Unsupported product areas deliberately remain unmasked rather than implying coverage. */
    fun forAreaId(areaId: String): List<MeteoNominalCoveragePolygon>? = when (areaId) {
        "uk" -> uk
        else -> MeteoContinentalNominalCoverage.geometryForAreaId(areaId)?.polygons
    }

    fun covers(areaId: String, point: GeoPoint): Boolean? = forAreaId(areaId)?.any { polygon ->
        point.inRing(polygon.exterior) && polygon.holes.none { hole -> point.inRing(hole) }
    }

    private fun GeoPoint.inRing(ring: List<GeoPoint>): Boolean {
        var inside = false
        ring.zipWithNext().forEach { (first, second) ->
            val crosses = (first.latitude > latitude) != (second.latitude > latitude)
            if (crosses) {
                val crossingLongitude = (second.longitude - first.longitude) *
                    (latitude - first.latitude) / (second.latitude - first.latitude) + first.longitude
                if (longitude < crossingLongitude) inside = !inside
            }
        }
        return inside
    }
}
